# Generated by Django 3.2.9 on 2021-11-20 16:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=10)),
                ('job_title', models.CharField(max_length=60)),
                ('profile_url', models.URLField(max_length=60)),
                ('location', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone_number', models.CharField(max_length=60)),
                ('company', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='employees', to='company.company')),
            ],
        ),
    ]
