# Generated by Django 3.2.9 on 2021-11-20 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_company_employees'),
        ('employee', '0002_auto_20211120_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='employees', to='company.company'),
        ),
    ]
