# Generated by Django 3.2.9 on 2021-11-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='employees',
        ),
    ]
